### ISSUE TITLE
Define KCC Resources for Budget and export to BigQuery

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#11]
Determine if we can use KCC to configure the export of budget/billing data to BigQuery, if not, we'll have to fall back to Terraform.

**Comment by srinises** [comment]
There doesn't appear to be a KCC route for configuring export to BigQuery

**Comment by seanpoulter-foci** [comment]
BigQuery was already configured when we bootstrapped.
