### ISSUE TITLE
Ensure we can see Labels in Looker Studio dashboard

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#191]
### Outcomes

* We can see Budget labels from Looker Studio
* We can see annotations in Backstage and k8s manifests

### Notes

Add metadata for:

* ~~Cost Centre~~ (#293)
* Team (Display) Name
* "Subscription" Billing
* Org Path: `phac / dmia / dpi`

Add them under `metadata.labels`. Here's a reference for the Config Connector Project ([link](https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/project)).

### Implementation Details

* Add labels to the tests - https://github.com/PHACDataHub/sci-portal/tree/main/backstage/packages/backend/src/plugins/scaffolder/templates
* Add labels to the PR contents in the **pull-request-changes** directories, https://github.com/PHACDataHub/sci-portal/tree/main/backstage/templates/project-create/pull-request-changes
* Update the Crossplane CRDs for each type
  https://github.com/PHACDataHub/sci-portal/tree/main/root-sync/base/crossplane/project
    * Add optional labels `type: object` to the XRD
    * Add labels to the composition after https://github.com/PHACDataHub/sci-portal/blob/main/root-sync/base/crossplane/project/composition-project.yaml#L28-L32
* Add the missing inputs to the template (with some fixed, and some key/value inputs)
* Update the `template_values` - https://github.com/PHACDataHub/sci-portal/blob/main/backstage/templates/project-create/template.yaml#L126

**Comment by tcaky** [comment]
Rules:
1. Lowercase only
2. Hyphen to separate words, i.e. `org-path: phac-dmia-dpi`

**Comment by seanpoulter-foci** [comment]
The Projects are labelled. The Looker Studio dashboard needs to be configured to meet the expected reporting needs.
