### ISSUE TITLE
FinOps - Define the template infra required to park a project

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#214]
### Outcomes

- The KCC or Terraform required to park a project when it reaches 120% budget

### Technical Notes

- Budget alerts sent to a pub/sub topic
- Handle the message to call a Backstage endpoint with the:
    - Project ID
    - Template (from a project label)
    - Alert data to help justify the PR

**Comment by srinises** [comment]
Created Doc to document both Terraform and KCC approaches for

1. Create a Pubsub Topic (this topic has to be added in the budget config as an alert destination)
2. Create a subscription to this topic
3. Create a cloud functions to call an API (to be replaced with the backstage API - written in JS) and trigger it when a message is published to the topic

**Comment by srinises** [comment]
Parking deprioritized as of 16-May, Closing.
