### ISSUE TITLE
Templates - Reference Implementation: Baseline with R Studio (Cloud Workstation)

### ISSUE THREAD

**Issue by bmesfin24** [PHACDataHub/sci-portal#25]
- Build on the Baseline Template
- Work with Collin and his example:
  https://github.com/PHACDataHub/infra-core/tree/cloud-workstation-template/cloud-workstation-template
- Configure the Terraform provider to isolate the state file for the project

**Comment by seanpoulter-foci** [comment]
The templates were removed from scope by Mike and Vedant.
