### ISSUE TITLE
FinOps - Dashboard: Add the dashboard

### ISSUE THREAD

**Issue by bmesfin24** [PHACDataHub/sci-portal#26]
### Outcomes

* Embed the Looker Studio dashboard
* Add missing documentation to the Bootstrap docs

### Tech Notes

We followed this for another cluster:

* https://cloud.google.com/billing/docs/how-to/visualize-data
* https://github.com/GoogleCloudPlatform/terraform-google-billing-dashboard

### Blocked

Foci cannot see the expected [Cloud Billing data tables](https://cloud.google.com/billing/docs/how-to/export-data-bigquery):

1. Standard usage cost table
2. Detailed usage cost table
3. (Optional) Pricing table

These are required to [Create your copy of the dashboard - Step 4](https://cloud.google.com/billing/docs/how-to/visualize-data#create-dashboard-copy). We need the first two dataset names.

**Comment by seanpoulter-foci** [comment]
![Image](https://github.com/PHACDataHub/sci-portal/assets/98067886/2859d55b-2939-43c3-86dc-a68745635420)
