### ISSUE TITLE
Add claims to the sci-portal-users repo

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#320]

**Comment by vedantthapa** [comment]
@seanpoulter-foci, I was wondering if you have any thoughts on how to bootstrap the SSH key for the `sci-portal-users` repo. I was hoping to use the [config-sync TF module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/v12.3.0/modules/config-sync) similar to what [we already have](https://github.com/PHACDataHub/sci-portal/blob/main/bootstrap/gke-cluster/main.tf#L154-L170), but I'm not exactly sure about the repercussions.

If I understand correctly, the config-sync module adds the private ssh key as a secret with the name `git-creds`, however, if I were to create another instance of the same module, would it overwrite the secret in k8s? Although, _technically_, passing secret name [seems possible](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/v12.3.0/modules/config-sync/main.tf#L38), the [module inputs](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/tree/v12.3.0/modules/config-sync#inputs) don't seem to expose a parameter for it.

fyi; I tried adding the same public key on the `sci-portal-users` repo but github didn't like that.

I'm not an expert on terraform so I might be just overthinking here lol.

**Comment by seanpoulter-foci** [comment]
We've resolved this off the issue and merged #387. Our next steps are to migrate the manifests, point to the next repo, and migrate the GitHub Workflow to close test PRs.
