### ISSUE TITLE
Handoff - Google-developed open source solutions which can be leveraged

### ISSUE THREAD

**Issue by bmesfin24** [PHACDataHub/sci-portal#37]
[Config Sync, kpt, ](https://cloud.google.com/config-connector/docs/how-to/import-export/overview)https://cloud.google.com/config-connector/docs/how-to/import-export/overview[ CLI tool, nomos](https://cloud.google.com/config-connector/docs/how-to/import-export/overview)

**Comment by seanpoulter-foci** [comment]
There are no new tools to document.
