### ISSUE TITLE
FinOps - Alerting: Automated Budget Management

### ISSUE THREAD

**Issue by bmesfin24** [PHACDataHub/sci-portal#69]
- Alert admin and owner when 25%, 50%, 75%, 90%, 95%, and 100% of budget used
- Alert admin and owner when 120% budget used
- Alert with shutdown warnings for each percent increase between 100% and 120%

### Outcomes

Send an email when we 

### Tech Notes

- Update the base template to set up the budget alerts, topics, etc..
- Use [GC Notify](https://notification.canada.ca/)

**Comment by srinises** [comment]
Working on KCC for

- Defining budget alert thresholds and directing alerts to pubsub
- Creating the pubsub topic, cloudfunctions and deploying the Cloudfunction (written in JS) to call GCNotify

**Comment by srinises** [comment]
KCC issues -

- the budget manifest got applied but unable to view the budget on the console (maybe an issue with KCC setup? not sure)
- KCC doesn't handle code zip and upload to storage bucket during deployment; this has to be a manual step or performed by some other code

Hence using Terraform

**Comment by srinises** [comment]
Updated [Document](https://docs.google.com/document/d/1wV_-8b99ioDCBl7W7_V3kd0GrpT0Yz2RTpv9kYZvyd8/edit?tab=t.0) with the required code to perform the following.

Create Terraform for
- Creating budgets, setting thresholds and setting alert path to pubsub
- Creating a pubsub topic
- Creating a Cloud Function to be triggered by pubsub topic

Write JS for the Cloud Function to
- Read the alert message
- Extract the budgetDisplayName and retrieve project labels
- Construct the email notification
- Call the GC Notify API

**Comment by seanpoulter-foci** [comment]
We'll need help adding the email templates to GC Notify. Here are the templates @srinises proposed in his document with some tweaks:

### Budget Threshold Alerts

Subject: `((threshold))% Budget Reached`
Body:

```
Dear User,

Your GCP Project ((project_id)) has consumed ((threshold))% of the budget. The cost to date is $((amount)) ((currency_code)) of the $((budget_amount)) ((currency_code)) budget.

Please take corrective action or contact your administrator.

Thank you
```

--

### ~~Shutdown~~ Over-Budget Warning

Since we're not doing automated parking we can pivot from a **Shutdown Warning** to an **Over-Budget Warning**:

Subject: `Warning: ((threshold))% Budget Reached`
Body:

```
Dear User,

Your GCP Project ((project_id)) has consumed ((threshold))% of the budget. The cost to date is $((amount)) ((currency_code)) of the $((budget_amount)) ((currency_code)) budget.

Please take corrective action or contact your administrator.

Thank you
```

**Comment by seanpoulter-foci** [comment]
Test Data:

```json
"personalisation": {
  "project_id": "pht-01hsv4d2m0n",
  "threshold": "75",
  "amount": "2,250",
  "budget_amount": "3,000",
  "currency_code": "CAD"
}
```

**Comment by seanpoulter-foci** [comment]
Budget alert emails are sent using GC Notify to the recipients from Backstage when an alert threshold is exceeded for the first time.

### Screenshots / Demo

![Image](https://github.com/PHACDataHub/sci-portal/assets/98067886/925d4f2a-b471-40be-946e-5346d9115a03)
