### ISSUE TITLE
Extensibility Report - Prepare Outline

### ISSUE THREAD

**Issue by seanpoulter-foci** [PHACDataHub/sci-portal#85]

**Comment by srinises** [comment]
Report Template Complete - [Link to Template](https://docs.google.com/document/d/1CerIDYjDpySzXTkvxNLPSVlPo6Jt5Vj56dRUpQm55Do/edit?resourcekey=0-D7pF_3UmLlWxTzE7UzaWFQ&tab=t.0) in [Project Drive](https://drive.google.com/corp/drive/folders/1J2xYlCRoEJY2UIBWNZia1iVo6ggiWuVj)

**Comment by srinises** [comment]
Marking complete
